import { toCents, fromCents } from '../../../utils/currency.js';
import { v4 as uuidv4 } from 'uuid';

export default function SectionAirfare({ event, updateEvent, displayCurrency, exchangeRate }) {
  const airfare = event.airfare;

  const addGroup = () => {
    const group = {
      id: uuidv4(),
      group_type: 'staff',
      traveler_count: 1,
      class: 'economy',
      cost_per_person_usd_cents: 0,
      subtotal_usd_cents: 0,
      notes: ''
    };
    updateEvent('airfare.groups', [...(airfare.groups || []), group]);
  };

  const removeGroup = (id) => {
    updateEvent('airfare.groups', airfare.groups.filter(g => g.id !== id));
  };

  const updateGroup = (id, field, value) => {
    const updated = airfare.groups.map(g => {
      if (g.id !== id) return g;
      const patch = {
        [field]: field === 'cost_per_person_usd_cents'
          ? toCents(value, exchangeRate)
          : field === 'traveler_count'
            ? parseInt(value) || 0
            : value
      };
      return { ...g, ...patch };
    });
    updateEvent('airfare.groups', updated);
  };

  return (
    <div className="section">
      <div className="subsection-header">
        <span>Airfare Groups</span>
        <button className="btn-add" onClick={addGroup}>+ Add Group</button>
      </div>

      {(airfare.groups || []).length === 0 && (
        <p className="empty-state">No airfare groups. Add a group to begin.</p>
      )}

      {(airfare.groups || []).map(group => {
        const isAutoGenerated = group.group_type === 'translator';
        return (
          <div key={group.id} className={`airfare-group ${isAutoGenerated ? 'auto-generated' : ''}`}>
            {isAutoGenerated && <span className="auto-label">Auto (translator)</span>}

            <div className="field-row field-row--triple">
              <div>
                <label>Group Type</label>
                <select
                  value={group.group_type}
                  onChange={e => updateGroup(group.id, 'group_type', e.target.value)}
                  disabled={isAutoGenerated}
                >
                  <option value="staff">Staff</option>
                  <option value="board">Board</option>
                  <option value="speaker">Speaker</option>
                  <option value="translator">Translator</option>
                  <option value="other">Other</option>
                </select>
              </div>
              <div>
                <label>Travelers</label>
                <input
                  type="number"
                  min="1"
                  value={group.traveler_count}
                  onChange={e => updateGroup(group.id, 'traveler_count', e.target.value)}
                />
              </div>
              <div>
                <label>Class</label>
                <select
                  value={group.class}
                  onChange={e => updateGroup(group.id, 'class', e.target.value)}
                >
                  <option value="economy">Economy</option>
                  <option value="business">Business</option>
                  <option value="first">First</option>
                </select>
              </div>
            </div>

            <div className="field-row field-row--split">
              <div>
                <label>Cost / Person</label>
                <input
                  type="text"
                  defaultValue={group.cost_per_person_usd_cents ? (group.cost_per_person_usd_cents / 100 * exchangeRate).toFixed(2) : ''}
                  onBlur={e => updateGroup(group.id, 'cost_per_person_usd_cents', e.target.value)}
                  placeholder="0.00"
                />
              </div>
              <div>
                <label>Notes</label>
                <input
                  type="text"
                  value={group.notes}
                  onChange={e => updateGroup(group.id, 'notes', e.target.value)}
                  placeholder="Optional"
                  disabled={isAutoGenerated}
                />
              </div>
            </div>

            <div className="line-subtotal">
              Subtotal: {fromCents(group.traveler_count * group.cost_per_person_usd_cents, exchangeRate, displayCurrency)}
            </div>

            {!isAutoGenerated && (
              <button className="btn-remove-group" onClick={() => removeGroup(group.id)}>Remove group</button>
            )}
          </div>
        );
      })}

      <div className="section-total">
        Airfare Total: {fromCents(event.budget_summary?.airfare_total_usd_cents || 0, exchangeRate, displayCurrency)}
      </div>
    </div>
  );
}
