#!/usr/bin/env node
/**
 * Meridian Migration Script
 *
 * Reads local JSON data files and generates PostgreSQL-compatible SQL.
 * Two outputs:
 *   001_schema.sql — CREATE TABLE statements with RLS
 *   002_data.sql   — INSERT statements from local JSON data
 *
 * Usage:
 *   node scripts/migrate.js --source ./data/local --output ./data/migrations/output
 *   node scripts/migrate.js --source ./data/local --target postgresql://...
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');

function parseArgs() {
  const args = process.argv.slice(2);
  const result = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      result[args[i].slice(2)] = args[i + 1] || true;
      i++;
    }
  }
  return result;
}

function readLocalTable(sourceDir, table) {
  const filePath = join(sourceDir, `${table}.json`);
  if (!existsSync(filePath)) return [];
  try {
    return JSON.parse(readFileSync(filePath, 'utf8'));
  } catch {
    return [];
  }
}

function generateSchema() {
  return `-- Meridian Schema — generated by migrate.js
-- Apply with: psql $DATABASE_URL -f 001_schema.sql

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Organizations
CREATE TABLE IF NOT EXISTS organizations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('global', 'regional', 'chapter')),
  parent_id UUID REFERENCES organizations(id),
  region TEXT,
  active BOOLEAN DEFAULT true,
  config JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Users
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  role TEXT NOT NULL,
  track TEXT NOT NULL CHECK (track IN ('volunteer', 'staff', 'mixed')),
  display_name TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Events
CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  created_by UUID REFERENCES users(id),
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('global', 'regional', 'chapter')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'complete', 'cancelled')),
  start_date DATE,
  end_date DATE,
  duration_days INTEGER,
  display_currency TEXT DEFAULT 'USD',
  usd_exchange_rate NUMERIC(12, 6) DEFAULT 1.0,
  regions_supporting JSONB DEFAULT '[]',
  translation_required BOOLEAN DEFAULT false,
  languages_required JSONB DEFAULT '[]',
  venue JSONB DEFAULT '{}',
  lodging JSONB DEFAULT '{}',
  airfare JSONB DEFAULT '{}',
  per_diem JSONB DEFAULT '{}',
  translation JSONB DEFAULT '{}',
  materials JSONB DEFAULT '{}',
  support_requirements JSONB DEFAULT '{}',
  budget_summary JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Org Health Signals
CREATE TABLE IF NOT EXISTS org_health_signals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  signal_date DATE NOT NULL,
  instrument TEXT NOT NULL CHECK (instrument IN ('orra-lite', 'orra', 'plh', 'sli')),
  lhi_score NUMERIC(5, 2),
  farmer_score NUMERIC(5, 2),
  soil_score NUMERIC(5, 2),
  seed_score NUMERIC(5, 2),
  friction_density NUMERIC(8, 4),
  legitimacy_index NUMERIC(5, 2),
  plh_distribution JSONB,
  readiness_output TEXT CHECK (readiness_output IN ('Grounded', 'Rebuilding', 'Scattered')),
  org_type TEXT CHECK (org_type IN ('global', 'regional', 'chapter')),
  org_size_band TEXT CHECK (org_size_band IN ('small', 'medium', 'large')),
  region_code TEXT,
  respondent_count INTEGER,
  pushed_to_ssg BOOLEAN DEFAULT false,
  pushed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Friction Log
CREATE TABLE IF NOT EXISTS friction_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  logged_by UUID REFERENCES users(id),
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  category TEXT NOT NULL CHECK (category IN ('Process', 'Communication', 'Authority', 'Resource', 'Interpersonal', 'Structural')),
  description TEXT,
  severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
  resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rhythm Board
CREATE TABLE IF NOT EXISTS rhythm_board (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  level TEXT NOT NULL,
  objectives JSONB DEFAULT '[]',
  milestones JSONB DEFAULT '[]',
  rhythm JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_events_org ON events(organization_id);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);
CREATE INDEX IF NOT EXISTS idx_friction_log_org ON friction_log(organization_id);
CREATE INDEX IF NOT EXISTS idx_health_signals_org ON org_health_signals(organization_id);
CREATE INDEX IF NOT EXISTS idx_health_signals_pushed ON org_health_signals(pushed_to_ssg);
CREATE INDEX IF NOT EXISTS idx_rhythm_board_org_level ON rhythm_board(organization_id, level);

-- Row Level Security
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE friction_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_health_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE rhythm_board ENABLE ROW LEVEL SECURITY;

CREATE POLICY org_isolation_events ON events
  USING (organization_id::text = current_setting('app.current_org_id', true));

CREATE POLICY org_isolation_friction ON friction_log
  USING (organization_id::text = current_setting('app.current_org_id', true));

CREATE POLICY org_isolation_signals ON org_health_signals
  USING (organization_id::text = current_setting('app.current_org_id', true));

CREATE POLICY org_isolation_rhythm ON rhythm_board
  USING (organization_id::text = current_setting('app.current_org_id', true));

CREATE POLICY org_isolation_users ON users
  USING (organization_id::text = current_setting('app.current_org_id', true));
`;
}

function escapeSQL(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'boolean') return val ? 'true' : 'false';
  if (typeof val === 'number') return val.toString();
  if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

function generateInserts(table, records) {
  if (records.length === 0) return `-- No data for ${table}\n`;
  const lines = [`-- ${table} (${records.length} records)`];
  for (const record of records) {
    const cols = Object.keys(record).join(', ');
    const vals = Object.values(record).map(escapeSQL).join(', ');
    lines.push(`INSERT INTO ${table} (${cols}) VALUES (${vals}) ON CONFLICT (id) DO NOTHING;`);
  }
  return lines.join('\n') + '\n';
}

async function main() {
  const args = parseArgs();
  const sourceDir = args.source
    ? join(process.cwd(), args.source)
    : join(PROJECT_ROOT, 'data/local');
  const outputDir = args.output
    ? join(process.cwd(), args.output)
    : join(PROJECT_ROOT, 'data/migrations/output');

  console.log(`Source: ${sourceDir}`);
  console.log(`Output: ${outputDir}`);

  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });

  // Generate schema SQL
  const schemaSql = generateSchema();
  writeFileSync(join(outputDir, '001_schema.sql'), schemaSql);
  console.log('Generated: 001_schema.sql');

  // Generate data SQL from local JSON files
  const tables = ['organizations', 'users', 'events', 'org_health_signals', 'friction_log', 'rhythm_board'];
  let dataSql = '-- Meridian Data Migration — generated by migrate.js\n\n';
  for (const table of tables) {
    const records = readLocalTable(sourceDir, table);
    dataSql += generateInserts(table, records) + '\n';
  }
  writeFileSync(join(outputDir, '002_data.sql'), dataSql);
  console.log('Generated: 002_data.sql');

  if (args.target) {
    console.log('\nTo apply to database:');
    console.log(`  psql "${args.target}" -f ${outputDir}/001_schema.sql`);
    console.log(`  psql "${args.target}" -f ${outputDir}/002_data.sql`);
  }

  console.log('\nMigration files generated successfully.');
}

main().catch(err => {
  console.error('Migration failed:', err.message);
  process.exit(1);
});
